//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BarcodeBasic
    {
        public int BarcodeID { get; set; }
        public string Code { get; set; }
        public Nullable<int> GoodsArrivalID { get; set; }
        public Nullable<int> GoodsArrivalDetailID { get; set; }
        public Nullable<int> GoodsArrivalPackageID { get; set; }
    }
}
