//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BlendingInstructionLog
    {
        public int PackageIssueDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string ProductionLineCode { get; set; }
        public Nullable<System.DateTime> PackageIssueWorkshiftEntryDate { get; set; }
        public string PackageIssueWorkshiftCode { get; set; }
        public string GoodsReceiptReference { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public decimal PackageIssueDetailQuantity { get; set; }
        public Nullable<int> SemifinishedProductWorkshiftEntryDate { get; set; }
        public Nullable<int> SemifinishedProductWorkshiftCode { get; set; }
        public Nullable<int> CommoditiyCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Weights { get; set; }
    }
}
