//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlendingInstructionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlendingInstructionDetail()
        {
            this.PackageIssueDetails = new HashSet<PackageIssueDetail>();
        }
    
        public int BlendingInstructionDetailID { get; set; }
        public int BlendingInstructionID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string Code { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityIssued { get; set; }
        public string Jobs { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> VoidTypeID { get; set; }
        public bool Approved { get; set; }
        public bool InActive { get; set; }
        public bool InActivePartial { get; set; }
        public Nullable<System.DateTime> InActivePartialDate { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual BlendingInstruction BlendingInstruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageIssueDetail> PackageIssueDetails { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
