//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class FinishedItemViewDetail
    {
        public int FinishedItemDetailID { get; set; }
        public int FinishedItemID { get; set; }
        public int FirmOrderID { get; set; }
        public int FirmOrderDetailID { get; set; }
        public int PlannedOrderID { get; set; }
        public int PlannedOrderDetailID { get; set; }
        public int SemifinishedItemID { get; set; }
        public int SemifinishedItemDetailID { get; set; }
        public Nullable<int> SemifinishedHandoverID { get; set; }
        public System.DateTime SemifinishedItemEntryDate { get; set; }
        public string SemifinishedItemReference { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public int PiecePerPack { get; set; }
        public string Remarks { get; set; }
        public int WorkshiftID { get; set; }
        public System.DateTime WorkshiftEntryDate { get; set; }
        public string WorkshiftCode { get; set; }
        public decimal QuantityRemains { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityFailure { get; set; }
        public decimal QuantityExcess { get; set; }
        public decimal QuantityShortage { get; set; }
        public decimal Swarfs { get; set; }
    }
}
