//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsArrivalPendingCustomer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerOfficialName { get; set; }
        public Nullable<System.DateTime> CustomerBirthday { get; set; }
        public string CustomerVATCode { get; set; }
        public string CustomerAttentionName { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerBillingAddress { get; set; }
        public string CustomerShippingAddress { get; set; }
        public int TransporterID { get; set; }
        public string TransporterCode { get; set; }
        public string TransporterName { get; set; }
        public string TransporterOfficialName { get; set; }
        public Nullable<System.DateTime> TransporterBirthday { get; set; }
        public string TransporterVATCode { get; set; }
        public string TransporterAttentionName { get; set; }
        public string TransporterTelephone { get; set; }
        public string TransporterBillingAddress { get; set; }
        public string TransporterShippingAddress { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
    }
}
