//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class InventoryControl
    {
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string CategoryName { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string BinLocationCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Code { get; set; }
        public string SealCode { get; set; }
        public string BatchCode { get; set; }
        public string LabCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<decimal> BisQuantity { get; set; }
        public Nullable<decimal> BisQuantityIssued { get; set; }
        public Nullable<decimal> BisQuantityRemains { get; set; }
        public Nullable<decimal> QuantityAvailableArrivals { get; set; }
        public Nullable<decimal> QuantityAvailableLocation1 { get; set; }
        public Nullable<decimal> QuantityAvailableLocation2 { get; set; }
        public Nullable<int> GoodsArrivalID { get; set; }
        public Nullable<int> GoodsReceiptID { get; set; }
        public Nullable<int> WarehouseTransferID { get; set; }
        public Nullable<int> WarehouseAdjustmentID { get; set; }
        public Nullable<int> BlendingInstructionID { get; set; }
        public bool LabApproved { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> TransferOrderID { get; set; }
        public Nullable<decimal> QuantityPurchaseOrders { get; set; }
        public Nullable<decimal> QuantityTransferOrders { get; set; }
        public Nullable<int> BarcodeID { get; set; }
        public Nullable<int> LabID { get; set; }
        public bool LabHold { get; set; }
        public bool LabInActive { get; set; }
    }
}
