//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class LabIndex
    {
        public int LabID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string Code { get; set; }
        public string CommodityCodes { get; set; }
        public string CommodityNames { get; set; }
        public string SealCodes { get; set; }
        public string BatchCodes { get; set; }
        public string Description { get; set; }
        public decimal TotalQuantity { get; set; }
        public string GoodsArrivalReference { get; set; }
        public Nullable<int> GoodsArrivalID { get; set; }
        public bool Approved { get; set; }
        public string ArrivalControllers { get; set; }
        public decimal TotalPackages { get; set; }
        public bool InActive { get; set; }
        public bool Hold { get; set; }
    }
}
