//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageIssue()
        {
            this.PackageIssueDetails = new HashSet<PackageIssueDetail>();
        }
    
        public int PackageIssueID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public int ShiftID { get; set; }
        public int WorkshiftID { get; set; }
        public int BlendingInstructionID { get; set; }
        public int CommodityID { get; set; }
        public int ProductionLineID { get; set; }
        public int WarehouseID { get; set; }
        public int CrucialWorkerID { get; set; }
        public int StorekeeperID { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int ApproverID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalQuantitySemifinished { get; set; }
        public decimal TotalQuantityFailure { get; set; }
        public decimal TotalQuantityReceipted { get; set; }
        public decimal TotalQuantityLoss { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Caption { get; set; }
        public int TotalRows { get; set; }
    
        public virtual BlendingInstruction BlendingInstruction { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageIssueDetail> PackageIssueDetails { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Workshift Workshift { get; set; }
        public virtual User User { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
