//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageIssueDetail
    {
        public int PackageIssueDetailID { get; set; }
        public int PackageIssueID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int ShiftID { get; set; }
        public int WorkshiftID { get; set; }
        public int CrucialWorkerID { get; set; }
        public int BlendingInstructionID { get; set; }
        public int BlendingInstructionDetailID { get; set; }
        public int GoodsReceiptID { get; set; }
        public int GoodsReceiptDetailID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int BatchID { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public int WarehouseID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantitySemifinished { get; set; }
        public decimal QuantityFailure { get; set; }
        public decimal QuantityReceipted { get; set; }
        public decimal QuantityLoss { get; set; }
        public string Remarks { get; set; }
        public bool Approved { get; set; }
        public int BinLocationID { get; set; }
        public string SealCode { get; set; }
        public string BatchCode { get; set; }
        public string LabCode { get; set; }
        public string Barcode { get; set; }
        public int ProductionLineID { get; set; }
        public Nullable<int> PackageIssueImage1ID { get; set; }
        public Nullable<int> PackageIssueImage2ID { get; set; }
        public string Reference { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual Workshift Workshift { get; set; }
        public virtual BlendingInstructionDetail BlendingInstructionDetail { get; set; }
        public virtual BlendingInstruction BlendingInstruction { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        public virtual PackageIssue PackageIssue { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual GoodsReceiptDetail GoodsReceiptDetail { get; set; }
    }
}
