//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PackageIssuePendingBlendingInstruction
    {
        public int BlendingInstructionID { get; set; }
        public string BlendingInstructionCode { get; set; }
        public string BlendingInstructionReference { get; set; }
        public System.DateTime BlendingInstructionEntryDate { get; set; }
        public string Description { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public decimal TotalQuantity { get; set; }
        public Nullable<decimal> TotalQuantityRemains { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
    }
}
