//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclateDetail
    {
        public int RecyclateDetailID { get; set; }
        public int RecyclateID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int NMVNTaskID { get; set; }
        public int LocationID { get; set; }
        public int WorkshiftID { get; set; }
        public int WarehouseID { get; set; }
        public int CrucialWorkerID { get; set; }
        public int StorekeeperID { get; set; }
        public Nullable<int> SemifinishedProductID { get; set; }
        public Nullable<int> FinishedProductPackageID { get; set; }
        public Nullable<int> FinishedItemDetailID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int RecycleCommodityID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityReceipted { get; set; }
        public string Remarks { get; set; }
        public bool Approved { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual Commodity Commodity1 { get; set; }
        public virtual FinishedItemDetail FinishedItemDetail { get; set; }
        public virtual FinishedProductPackage FinishedProductPackage { get; set; }
        public virtual Recyclate Recyclate { get; set; }
        public virtual SemifinishedProduct SemifinishedProduct { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Workshift Workshift { get; set; }
    }
}
