//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemifinishedItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemifinishedItem()
        {
            this.SemifinishedHandoverDetails = new HashSet<SemifinishedHandoverDetail>();
            this.SemifinishedItemDetails = new HashSet<SemifinishedItemDetail>();
        }
    
        public int SemifinishedItemID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public int CustomerID { get; set; }
        public int MaterialIssueID { get; set; }
        public int PlannedOrderID { get; set; }
        public int FirmOrderID { get; set; }
        public int BomID { get; set; }
        public int ShiftID { get; set; }
        public int WorkshiftID { get; set; }
        public int ProductionLineID { get; set; }
        public int CrucialWorkerID { get; set; }
        public Nullable<int> SemifinishedHandoverID { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int ApproverID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public int Temperature { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalQuantityFailure { get; set; }
        public decimal TotalQuantityFinished { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool HandoverApproved { get; set; }
    
        public virtual Bom Bom { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FirmOrder FirmOrder { get; set; }
        public virtual Location Location { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemifinishedHandoverDetail> SemifinishedHandoverDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemifinishedItemDetail> SemifinishedItemDetails { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Workshift Workshift { get; set; }
    }
}
