//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class SemifinishedHandoverPendingDetail
    {
        public Nullable<int> SemifinishedProductID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int ProductionLineID { get; set; }
        public string ProductionLineCode { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public int CrucialWorkerID { get; set; }
        public string CrucialWorkerName { get; set; }
        public Nullable<int> SemifinishedItemID { get; set; }
        public System.DateTime SemifinishedProtemEntryDate { get; set; }
        public string SemifinishedProtemReference { get; set; }
        public string Caption { get; set; }
    }
}
