//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class SemifinishedItemPendingMaterialIssue
    {
        public int MaterialIssueID { get; set; }
        public int PlannedOrderID { get; set; }
        public int FirmOrderID { get; set; }
        public System.DateTime FirmOrderEntryDate { get; set; }
        public string FirmOrderReference { get; set; }
        public string FirmOrderCode { get; set; }
        public string FirmOrderSpecification { get; set; }
        public string BomCode { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int MaterialIssueWorkshiftID { get; set; }
        public System.DateTime MaterialIssueWorkshiftEntryDate { get; set; }
        public string MaterialIssueWorkshiftCode { get; set; }
        public int ProductionLineID { get; set; }
        public string ProductionLineCode { get; set; }
        public int CrucialWorkerID { get; set; }
        public string CrucialWorkerCode { get; set; }
        public string CrucialWorkerName { get; set; }
        public decimal MaterialTotalQuantity { get; set; }
        public Nullable<decimal> MaterialQuantityRemains { get; set; }
        public int BomID { get; set; }
    }
}
