//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class TransferOrderIndex
    {
        public int TransferOrderID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public bool Approved { get; set; }
        public string VoidTypeName { get; set; }
        public bool InActive { get; set; }
        public bool InActivePartial { get; set; }
        public string TransferOrderJobs { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseReceiptCode { get; set; }
        public Nullable<int> TransferOrderDetailID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityIssued { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public Nullable<decimal> QuantityAvailables { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Packages { get; set; }
    }
}
